platform :ios, '9.0'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
target 'Angkasa Pura Solusi' do
  pod 'Alamofire'
  pod 'SVProgressHUD'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'IQKeyboardManagerSwift'
  pod 'Kingfisher'
  pod 'XLPagerTabStrip'
  pod 'Firebase/Core'
  pod 'Fabric', '~> 1.9.0'
  pod 'Crashlytics', '~> 3.12.0'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'EzPopup'
  pod 'FittedSheets'
  pod 'iOSDropDown'
  pod 'Toast-Swift', '~> 5.0.0'
  pod 'HSAttachmentPicker'
  pod 'JTAppleCalendar'
end
